// このファイルはリソース DLL ウィザードにより作成されたファイルです。直接編集しないでください。

library Zlog;

{ITE} {DFMFileType} {main.dfm}
{ITE} {DFMFileType} {Progress.dfm}
{ITE} {DFMFileType} {UAbout.dfm}
{ITE} {DFMFileType} {UACAGMulti.dfm}
{ITE} {DFMFileType} {UAgeDialog.dfm}
{ITE} {DFMFileType} {UAllAsianScore.dfm}
{ITE} {DFMFileType} {UALLJAMulti.dfm}
{ITE} {DFMFileType} {UALLJAScore.dfm}
{ITE} {DFMFileType} {UAPSprintScore.dfm}
{ITE} {DFMFileType} {UARRL10Multi.dfm}
{ITE} {DFMFileType} {UARRL10Score.dfm}
{ITE} {DFMFileType} {UARRLDXMulti.dfm}
{ITE} {DFMFileType} {UARRLDXScore.dfm}
{ITE} {DFMFileType} {UARRLWMulti.dfm}
{ITE} {DFMFileType} {UBandPlanEditDialog.dfm}
{ITE} {DFMFileType} {UBandScope2.dfm}
{ITE} {DFMFileType} {UBasicMulti.dfm}
{ITE} {DFMFileType} {UBasicScore.dfm}
{ITE} {DFMFileType} {UCFGEdit.dfm}
{ITE} {DFMFileType} {UChat.dfm}
{ITE} {DFMFileType} {UCheckCall2.dfm}
{ITE} {DFMFileType} {UCheckCountry.dfm}
{ITE} {DFMFileType} {UCheckMulti.dfm}
{ITE} {DFMFileType} {UCheckWin.dfm}
{ITE} {DFMFileType} {UClusterCOMSet.dfm}
{ITE} {DFMFileType} {UClusterTelnetSet.dfm}
{ITE} {DFMFileType} {UComm.dfm}
{ITE} {DFMFileType} {UConsolePad.dfm}
{ITE} {DFMFileType} {UCWKeyBoard.dfm}
{ITE} {DFMFileType} {UCwMessagePad.dfm}
{ITE} {DFMFileType} {UEditDialog.dfm}
{ITE} {DFMFileType} {UELogJarl1.dfm}
{ITE} {DFMFileType} {UELogJarl2.dfm}
{ITE} {DFMFileType} {UExceptionDialog.dfm}
{ITE} {DFMFileType} {UExportCabrillo.dfm}
{ITE} {DFMFileType} {UExportHamlog.dfm}
{ITE} {DFMFileType} {UFDMulti.dfm}
{ITE} {DFMFileType} {UFreqList.dfm}
{ITE} {DFMFileType} {UFreqTest.dfm}
{ITE} {DFMFileType} {UFunctionKeyPanel.dfm}
{ITE} {DFMFileType} {UGeneralMulti2.dfm}
{ITE} {DFMFileType} {UGeneralScore.dfm}
{ITE} {DFMFileType} {UGraphColorDialog.dfm}
{ITE} {DFMFileType} {UIARUMulti.dfm}
{ITE} {DFMFileType} {UIARUScore.dfm}
{ITE} {DFMFileType} {UInformation.dfm}
{ITE} {DFMFileType} {UIntegerDialog.dfm}
{ITE} {DFMFileType} {UIOTACategory.dfm}
{ITE} {DFMFileType} {UIOTAMulti.dfm}
{ITE} {DFMFileType} {UJA0Multi.dfm}
{ITE} {DFMFileType} {UJA0Score.dfm}
{ITE} {DFMFileType} {UJIDX_DX_Multi.dfm}
{ITE} {DFMFileType} {UJIDX_DX_Score.dfm}
{ITE} {DFMFileType} {UJIDXMulti.dfm}
{ITE} {DFMFileType} {UJIDXScore.dfm}
{ITE} {DFMFileType} {UJIDXScore2.dfm}
{ITE} {DFMFileType} {UKCJMulti.dfm}
{ITE} {DFMFileType} {UKCJScore.dfm}
{ITE} {DFMFileType} {UKCJZone.dfm}
{ITE} {DFMFileType} {UMenu.dfm}
{ITE} {DFMFileType} {UMessageManager.dfm}
{ITE} {DFMFileType} {UNewIOTARef.dfm}
{ITE} {DFMFileType} {UNewPrefix.dfm}
{ITE} {DFMFileType} {UNRDialog.dfm}
{ITE} {DFMFileType} {UOperatorEdit.dfm}
{ITE} {DFMFileType} {UOperatorPowerDialog.dfm}
{ITE} {DFMFileType} {UOptions.dfm}
{ITE} {DFMFileType} {UPackageLoader.dfm}
{ITE} {DFMFileType} {UPartials.dfm}
{ITE} {DFMFileType} {UPediScore.dfm}
{ITE} {DFMFileType} {UPluginManager.dfm}
{ITE} {DFMFileType} {UQsyInfo.dfm}
{ITE} {DFMFileType} {UQTCForm.dfm}
{ITE} {DFMFileType} {UQuickRef.dfm}
{ITE} {DFMFileType} {URateDialog.dfm}
{ITE} {DFMFileType} {URateDialogEx.dfm}
{ITE} {DFMFileType} {URigControl.dfm}
{ITE} {DFMFileType} {UScratchSheet.dfm}
{ITE} {DFMFileType} {USelectUserDefinedContest.dfm}
{ITE} {DFMFileType} {USixDownMulti.dfm}
{ITE} {DFMFileType} {USo2rNeoCp.dfm}
{ITE} {DFMFileType} {USpotForm.dfm}
{ITE} {DFMFileType} {USpotterListDlg.dfm}
{ITE} {DFMFileType} {UStartTimeDialog.dfm}
{ITE} {DFMFileType} {UStatusEdit.dfm}
{ITE} {DFMFileType} {USummaryInfo.dfm}
{ITE} {DFMFileType} {USuperCheck.dfm}
{ITE} {DFMFileType} {USuperCheck2.dfm}
{ITE} {DFMFileType} {UTargetEditor.dfm}
{ITE} {DFMFileType} {UTextEditor.dfm}
{ITE} {DFMFileType} {UTTYConsole.dfm}
{ITE} {DFMFileType} {UUTCDialog.dfm}
{ITE} {DFMFileType} {UVoiceForm.dfm}
{ITE} {DFMFileType} {UWAEMulti.dfm}
{ITE} {DFMFileType} {UWAEScore.dfm}
{ITE} {DFMFileType} {UWinKeyerTester.dfm}
{ITE} {DFMFileType} {UWPXMulti.dfm}
{ITE} {DFMFileType} {UWPXScore.dfm}
{ITE} {DFMFileType} {UWWMulti.dfm}
{ITE} {DFMFileType} {UWWScore.dfm}
{ITE} {DFMFileType} {UWWZone.dfm}
{ITE} {DFMFileType} {UZAnalyze.dfm}
{ITE} {DFMFileType} {UZLinkForm.dfm}
{ITE} {DFMFileType} {UZlinkTelnetSet.dfm}
{ITE} {DFMFileType} {UzLogGlobal.dfm}
{ITE} {DFMFileType} {UzLogKeyer.dfm}
{ITE} {DFMFileType} {UZServerInquiry.dfm}
{ITE} {RCFileType} {Win64\Release\Zlog_DRC.rc}

{$R 'main.dfm' 'MainForm:TForm'}
{$R 'Progress.dfm' 'formProgress:TForm'}
{$R 'UAbout.dfm' 'AboutBox:TForm'}
{$R 'UACAGMulti.dfm' 'ACAGMulti:TForm(BasicMulti)'}
{$R 'UAgeDialog.dfm' 'AgeDialog:TForm'}
{$R 'UAllAsianScore.dfm' 'AllAsianScore:TForm(IARUScore)'}
{$R 'UALLJAMulti.dfm' 'ALLJAMulti:TForm(BasicMulti)'}
{$R 'UALLJAScore.dfm' 'ALLJAScore:TForm(BasicScore)'}
{$R 'UAPSprintScore.dfm' 'APSprintScore:TForm(BasicScore)'}
{$R 'UARRL10Multi.dfm' 'ARRL10Multi:TForm(WWMulti)'}
{$R 'UARRL10Score.dfm' 'ARRL10Score:TForm(BasicScore)'}
{$R 'UARRLDXMulti.dfm' 'ARRLDXMulti:TForm(ACAGMulti)'}
{$R 'UARRLDXScore.dfm' 'ARRLDXScore:TForm(BasicScore)'}
{$R 'UARRLWMulti.dfm' 'ARRLWMulti:TForm(WWMulti)'}
{$R 'UBandPlanEditDialog.dfm' 'BandPlanEditDialog:TForm'}
{$R 'UBandScope2.dfm' 'BandScope2:TForm'}
{$R 'UBasicMulti.dfm' 'BasicMulti:TForm'}
{$R 'UBasicScore.dfm' 'BasicScore:TForm'}
{$R 'UCFGEdit.dfm' 'CFGEdit:TForm'}
{$R 'UChat.dfm' 'ChatForm:TForm'}
{$R 'UCheckCall2.dfm' 'CheckCall2:TForm(CheckWin)'}
{$R 'UCheckCountry.dfm' 'CheckCountry:TForm(CheckWin)'}
{$R 'UCheckMulti.dfm' 'CheckMulti:TForm(CheckWin)'}
{$R 'UCheckWin.dfm' 'CheckWin:TForm'}
{$R 'UClusterCOMSet.dfm' 'formClusterCOMSet:TForm'}
{$R 'UClusterTelnetSet.dfm' 'formClusterTelnetSet:TForm'}
{$R 'UComm.dfm' 'CommForm:TForm'}
{$R 'UConsolePad.dfm' 'ConsolePad:TForm'}
{$R 'UCWKeyBoard.dfm' 'CWKeyBoard:TForm'}
{$R 'UCwMessagePad.dfm' 'CwMessagePad:TForm'}
{$R 'UEditDialog.dfm' 'EditDialog:TForm'}
{$R 'UELogJarl1.dfm' 'formELogJarl1:TForm'}
{$R 'UELogJarl2.dfm' 'formELogJarl2:TForm'}
{$R 'UExceptionDialog.dfm' 'ExceptionDialog:TForm'}
{$R 'UExportCabrillo.dfm' 'formExportCabrillo:TForm'}
{$R 'UExportHamlog.dfm' 'formExportHamlog:TForm'}
{$R 'UFDMulti.dfm' 'FDMulti:TForm(ACAGMulti)'}
{$R 'UFreqList.dfm' 'FreqList:TForm(CheckWin)'}
{$R 'UFreqTest.dfm' 'formFreqTest:TForm'}
{$R 'UFunctionKeyPanel.dfm' 'formFunctionKeyPanel:TForm'}
{$R 'UGeneralMulti2.dfm' 'GeneralMulti2:TForm(ACAGMulti)'}
{$R 'UGeneralScore.dfm' 'GeneralScore:TForm(BasicScore)'}
{$R 'UGraphColorDialog.dfm' 'GraphColorDialog:TForm'}
{$R 'UIARUMulti.dfm' 'IARUMulti:TForm(WWMulti)'}
{$R 'UIARUScore.dfm' 'IARUScore:TForm(BasicScore)'}
{$R 'UInformation.dfm' 'formInformation:TForm'}
{$R 'UIntegerDialog.dfm' 'IntegerDialog:TForm'}
{$R 'UIOTACategory.dfm' 'IOTACategory:TForm'}
{$R 'UIOTAMulti.dfm' 'IOTAMulti:TForm(ACAGMulti)'}
{$R 'UJA0Multi.dfm' 'JA0Multi:TForm(BasicMulti)'}
{$R 'UJA0Score.dfm' 'JA0Score:TForm(BasicScore)'}
{$R 'UJIDX_DX_Multi.dfm' 'JIDX_DX_Multi:TForm(BasicMulti)'}
{$R 'UJIDX_DX_Score.dfm' 'JIDX_DX_Score:TForm(BasicScore)'}
{$R 'UJIDXMulti.dfm' 'JIDXMulti:TForm(WWMulti)'}
{$R 'UJIDXScore.dfm' 'JIDXScore:TForm(WWScore)'}
{$R 'UJIDXScore2.dfm' 'JIDXScore2:TForm(BasicScore)'}
{$R 'UKCJMulti.dfm' 'KCJMulti:TForm(BasicMulti)'}
{$R 'UKCJScore.dfm' 'KCJScore:TForm(BasicScore)'}
{$R 'UKCJZone.dfm' 'KCJZone:TForm'}
{$R 'UMenu.dfm' 'MenuForm:TForm'}
{$R 'UMessageManager.dfm' 'formMessageManager:TForm'}
{$R 'UNewIOTARef.dfm' 'NewIOTARef:TForm'}
{$R 'UNewPrefix.dfm' 'NewPrefix:TForm'}
{$R 'UNRDialog.dfm' 'NRDialog:TForm'}
{$R 'UOperatorEdit.dfm' 'formOperatorEdit:TForm'}
{$R 'UOperatorPowerDialog.dfm' 'OperatorPowerDialog:TForm'}
{$R 'UOptions.dfm' 'formOptions:TForm'}
{$R 'UPackageLoader.dfm' 'PackageLoader:TForm'}
{$R 'UPartials.dfm' 'PartialCheck:TForm'}
{$R 'UPediScore.dfm' 'PediScore:TForm(BasicScore)'}
{$R 'UPluginManager.dfm' 'MarketForm:TForm'}
{$R 'UQsyInfo.dfm' 'formQsyInfo:TForm'}
{$R 'UQTCForm.dfm' 'QTCForm:TForm'}
{$R 'UQuickRef.dfm' 'QuickRef:TForm'}
{$R 'URateDialog.dfm' 'RateDialog:TForm'}
{$R 'URateDialogEx.dfm' 'RateDialogEx:TForm'}
{$R 'URigControl.dfm' 'RigControl:TForm'}
{$R 'UScratchSheet.dfm' 'ScratchSheet:TForm(ConsolePad)'}
{$R 'USelectUserDefinedContest.dfm' 'SelectUserDefinedContest:TForm'}
{$R 'USixDownMulti.dfm' 'SixDownMulti:TForm(FDMulti)'}
{$R 'USo2rNeoCp.dfm' 'formSo2rNeoCp:TForm'}
{$R 'USpotForm.dfm' 'SpotForm:TForm'}
{$R 'USpotterListDlg.dfm' 'formSpotterListDlg:TForm'}
{$R 'UStartTimeDialog.dfm' 'StartTimeDialog:TForm'}
{$R 'UStatusEdit.dfm' 'formStatusEdit:TForm'}
{$R 'USummaryInfo.dfm' 'SummaryInfo:TForm'}
{$R 'USuperCheck.dfm' 'SuperCheck:TForm'}
{$R 'USuperCheck2.dfm' 'SuperCheck2:TForm'}
{$R 'UTargetEditor.dfm' 'TargetEditor:TForm'}
{$R 'UTextEditor.dfm' 'TextEditor:TForm'}
{$R 'UTTYConsole.dfm' 'TTYConsole:TForm'}
{$R 'UUTCDialog.dfm' 'UTCDialog:TForm'}
{$R 'UVoiceForm.dfm' 'VoiceForm:TForm'}
{$R 'UWAEMulti.dfm' 'WAEMulti:TForm(ARRLWMulti)'}
{$R 'UWAEScore.dfm' 'WAEScore:TForm(BasicScore)'}
{$R 'UWinKeyerTester.dfm' 'formWinkeyerTester:TForm'}
{$R 'UWPXMulti.dfm' 'WPXMulti:TForm(WWMulti)'}
{$R 'UWPXScore.dfm' 'WPXScore:TForm(BasicScore)'}
{$R 'UWWMulti.dfm' 'WWMulti:TForm(BasicMulti)'}
{$R 'UWWScore.dfm' 'WWScore:TForm(BasicScore)'}
{$R 'UWWZone.dfm' 'WWZone:TForm'}
{$R 'UZAnalyze.dfm' 'ZAnalyze:TForm'}
{$R 'UZLinkForm.dfm' 'ZLinkForm:TForm'}
{$R 'UZlinkTelnetSet.dfm' 'formZLinkTelnetSet:TForm'}
{$R 'UzLogGlobal.dfm' 'dmZLogGlobal:TDataModule'}
{$R 'UzLogKeyer.dfm' 'dmZLogKeyer:TDataModule'}
{$R 'UZServerInquiry.dfm' 'ZServerInquiry:TForm'}
{$R 'Win64\Release\Zlog_DRC.res' 'Win64\Release\Zlog_DRC.rc'}

{$E ENU}

begin
end.
